use_frameworks!

platform :ios, '8.0'

target 'JXJXCategoryView_Example' do
  pod 'JXJXCategoryView', :path => '../'

  target 'JXJXCategoryView_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
